[package]
name = "prime-factor"
description = "A number factorizer written in Rust"
version = "0.4.0"
authors = ["Stefan Lindblad <stefan.lindblad@linux.com>"]
license = "LGPL-2.1-or-later"
edition = "2018"
repository = "https://github.com/Fairglow/prime-factor.git"
readme = "README.md"

[lib]
name = "primefactor"
path = "src/lib.rs"

[[bin]]
name = "prime-factor"
path = "src/main.rs"

[[bench]]
name = "prime-factor-benchmark"
path = "benches/benchmark.rs"
harness = false

[dependencies]
clap = "2.33.3"
log = "0.4.13"
stderrlog = "0.5.1"
genawaiter = "0.99.1"
rayon = "1.5.0"

[dev-dependencies]
rand = { version = "0.8.3", features = ["small_rng"] }
reikna = "0.12.3"
criterion = "0.3.4"
