[package]
name = "prime-factor"
description = "A prime number factorizer written in Rust"
version = "0.5.0"
authors = ["Stefan Lindblad <stefan.lindblad@linux.com>"]
license = "LGPL-2.1-or-later"
edition = "2021"
repository = "https://github.com/Fairglow/prime-factor.git"
readme = "README.md"
rust-version = "1.56"

[lib]
name = "primefactor"
path = "src/lib.rs"

[[bin]]
name = "prime-factor"
path = "src/main.rs"

[[bench]]
name = "prime-factor-benchmark"
path = "benches/benchmark.rs"
harness = false

[dependencies]
clap = "4.4"
log = "0.4"
env_logger = "0.11"
genawaiter = "0.99"
rayon = "1.8"
num = "0.4.1"

[dev-dependencies]
criterion = "0.5"
rand = { version = "0.8", features = ["small_rng"] }
reikna = "0.12"

[profile.release]
codegen-units = 1
lto = true
